- src/rebar3_clojerl_compile_prv.erl
> [Closes #2] Print compile-time errors

- src/rebar3_clojerl_compile_prv.erl
- src/rebar3_clojerl_repl_prv.erl
> [Closes #6] Include stacktrace in errors

- src/rebar3_clojerl_compile_prv.erl
> [Closes #4] Don't recompile unmodified source files [Closes #8] Compile deps

- src/rebar3_clojerl_prv_compile.erl
- src/rebar3_clojerl_utils.erl
> [#15] Only print stacktrace when debugging

- src/rebar3_clojerl_prv_compile.erl
> [Closes #18] Define *compile-protocols-path* as the current project's ebin directory

- src/rebar3_clojerl_prv_compile.erl
> [Closes #20] Abort on compiler error

- rebar.config
- src/rebar3_clojerl.hrl
- src/rebar3_clojerl_prv_compile.erl
- src/rebar3_clojerl_prv_test.erl
> [Closes #34] WITH_STACKTRACE macro for OTP 21

- README.md
> [#38] Mention templates in README

- priv/templates/rebar.config.tpl
- priv/templates/sup.clje.tpl
Fixes a couple of typos and uses git tags instead of branches
> Fix rebar3 template

- README.md
- priv/templates/README.md.tpl
- priv/templates/rebar.config.tpl
- src/rebar3_clojerl_prv_repl.erl
- src/rebar3_clojerl_prv_test.erl
> [Closes #42] update documentation and template

- README.md
- src/rebar3_clojerl.app.src
> [Closes #47] document rebar3.config options

- src/rebar3_clojerl_prv_compile.erl
> [Closes #52] Support starting a repl in an almost empty rebar.config

- src/rebar3_clojerl_prv_compile.erl
@arpunk 
This PR adds processing of [provider hooks](https://www.rebar3.org/docs/configuration#section-provider-hooks) for the task `clojerl compile`, which will make possible to have a `pre` hook in the `clojerl`'s rebar.config (modified branch [here](https://github.com/clojerl/clojerl/blob/use-pre-hook/rebar.config#L50)). 
Using a `pre` hook triggers the default `compile` task for the `clojerl` dependency when any of the other `clojerl xxxx` tasks are executed (since they currently all have `clojerl compile` as a dep). This includes the `clojerl test` task which is what the linked issue (#50) was about 😄.
> [#50] Process provider_hooks for the 'compile' task

- README.md
- priv/templates/clojerl_app.template
- priv/templates/rebar.config.tpl
- src/rebar3_clojerl_prv_test.erl
> [#57] Avoid adding test dirs twice

- src/rebar3_clojerl_prv_test.erl
> [#60] Also handle result from clojure.test/test-var

- README.md
- src/rebar3_clojerl.erl
- src/rebar3_clojerl_prv_run.erl
> [#65] Add run command

- src/rebar3_clojerl_prv_repl.erl
> [#69] Restart clojerl before starting the REPL when clje.user doesn't refer vars from clojure.core

- src/rebar3_clojerl.erl
- src/rebar3_clojerl_prv_run.erl
> [#73] Resolve var and then apply the arguments

- src/rebar3_clojerl_prv_compile.erl
> [#75] Include stacktrace on compile error

- README.md
- src/rebar3_clojerl.erl
- src/rebar3_clojerl_prv_escriptize.erl
> [#67] Add escriptize command

- README.md
- priv/templates/README.md.tpl
- priv/templates/clojerl_app.template
- priv/templates/clojerl_escript.template
- priv/templates/escript.README.md.tpl
- priv/templates/escript.app.src.tpl
- priv/templates/escript.rebar.config.tpl
- priv/templates/name.clje.tpl
> [#63] escript template

- src/rebar3_clojerl_prv_compile.erl
- src/rebar3_clojerl_prv_repl.erl
- src/rebar3_clojerl_utils.erl
> [#88] Improve error messaging and handling when clojerl is not available

- src/rebar3_clojerl_prv_compile.erl
- src/rebar3_clojerl_prv_escriptize.erl
- src/rebar3_clojerl_prv_release.erl
> [#91] Make 'clojerl compile' depend on default 'compile'

- rebar.config
> [#93] Generate edoc

- priv/templates/escript.rebar.config.tpl
- priv/templates/rebar.config.tpl
- priv/templates/release.rebar.config.tpl
> [#95] Bump versions

- src/rebar3_clojerl_prv_release.erl
> [#97] Fallback to new function to get release command options spec

- priv/templates/escript.rebar.config.tpl
- priv/templates/rebar.config.tpl
- priv/templates/release.rebar.config.tpl
> [#100] Update plugin version in templates

- Makefile
- rebar.config
> [#103] Add Makefile with targets to publish to hex

- src/rebar3_clojerl_prv_compile.erl
> [#106] Add the src directories from dependencies before compiling clojerl

- Makefile
- rebar.config
> [#109] Create a profile for generating docs

- priv/templates/clojerl_lib.template
- priv/templates/lib.src.tpl
> [#112] Remove unnecessary mod attribute

- priv/templates/escript.rebar.config.tpl
- priv/templates/rebar.config.tpl
- priv/templates/release.rebar.config.tpl
> [#114] Bump versions in templates

- src/rebar3_clojerl_prv_compile.erl
> [#118] Sort files to be compiled

- src/rebar3_clojerl_prv_compile.erl
> [#120] Search the target files in all directories currently in the code path
